
export const AUTH       = 'AUTH'
export const LOGOUT     = 'LOGOUT'

export const UPDATE_PROFILE  = 'UPDATE_PROFILE'

export const FETCH_ABOUTME  = 'FETCH_ABOUTME'
export const UPDATE_ABOUTME = 'UPDATE_ABOUTME'
export const DELETE_ABOUTME = 'DELETE_ABOUTME'
export const ADD_ABOUTME    = 'ADD_ABOUTME'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECT  = 'FETCH_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'  
export const ADD_PROJECT    = 'ADD_PROJECT'

export const FETCH_EXPERIENCES  = 'FETCH_EXPERIENCES'
export const FETCH_EXPERIENCE   = 'FETCH_EXPERIENCE'
export const UPDATE_EXPERIENCE  = 'UPDATE_EXPERIENCE'
export const DELETE_EXPERIENCE  = 'DELETE_EXPERIENCE'
export const ADD_EXPERIENCE     = 'ADD_EXPERIENCE'

export const FETCH_EDUCATIONS  = 'FETCH_EDUCATIONS'
export const FETCH_EDUCATION   = 'FETCH_EDUCATION'
export const UPDATE_EDUCATION  = 'UPDATE_EDUCATION'
export const DELETE_EDUCATION  = 'DELETE_EDUCATION'
export const ADD_EDUCATION     = 'ADD_EDUCATION'

export const FETCH_SKILLS    = 'FETCH_SKILLS'
export const UPDATE_SKILLS   = 'UPDATE_SKILLS'
export const DELETE_SKILLS   = 'DELETE_SKILLS'
export const ADD_SKILLS      = 'ADD_SKILLS'

export const FETCH_CONTACT  = 'FETCH_CONTACT'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const ADD_CONTACT    = 'ADD_CONTACT'